### ISSUE TITLE
feature/loading-screen

### ISSUE THREAD

**Issue by Drufsen** [GICU-3/GICU-3-Application#6]
A loading screen which initially is used on startup. It features Joel's face spinning around in circles.

**Comment by Drufsen** [comment]
Rotating image of Joelpe has been added.
An issue regarding text alignment has been noted.

**Comment by 031simon** [comment]
> Rotating image of Joelpe has been added. An issue regarding text alignment has been noted.

problem fixed and feature complete. loading message up for debate
